In [50]:
import pandas as pd
import numpy as np

df = pd.read_excel('vinhos_desafio.xlsx')    

df

# Análise da tabela inteira

      ano tipo_uva     tipo_local   categoria  volume_hl  valor_usd      local
0    2016    Table           Pais  Exportacao     5183.0   399091.0     Italia
1    2016    Table           Pais  Importacao     5752.0   230080.0  Argentina
2    2018    Table           Pais  Importacao     1082.0    47608.0  Argentina
3    2023    Table           Pais  Exportacao     7476.0   142044.0  Argentina
4    2024    Table           Pais  Importacao     2751.0   236586.0    Espanha
..    ...      ...            ...         ...        ...        ...        ...
795  2016     Wine  Estado_Brasil      Vendas     4294.0   283404.0         PR
796  2020    Table           Pais  Exportacao     5590.0   307450.0  Australia
797  2019    Table           Pais  Exportacao     5331.0   314529.0        EUA
798  2021     Wine           Pais  Importacao     3589.0   333777.0      Chile
799  2024    Table           Pais  Importacao     4465.0   156275.0      Chile

[800 rows x 7 columns]

In [49]:
df.head(10) #aqui mostra as primeiras linhas, neste caso pedir ás 10 primeiras

    ano tipo_uva     tipo_local   categoria  volume_hl  valor_usd      local
0  2016    Table           Pais  Exportacao     5183.0   399091.0     Italia
1  2016    Table           Pais  Importacao     5752.0   230080.0  Argentina
2  2018    Table           Pais  Importacao     1082.0    47608.0  Argentina
3  2023    Table           Pais  Exportacao     7476.0   142044.0  Argentina
4  2024    Table           Pais  Importacao     2751.0   236586.0    Espanha
5  2021    Table           Pais  Exportacao     2813.0    92829.0      Chile
6  2016    Table  Estado_Brasil      Vendas     5127.0   333255.0         BA
7  2018     Wine           Pais  Importacao     1029.0    42189.0     Franca
8  2019     Wine           Pais  Importacao     3165.0   259530.0  Argentina
9  2019     Wine           Pais  Importacao      505.0    18180.0      Chile

In [31]:
df.info() #aqui mostra o tipo de cada coluna, a quantidade de valores não nulos e a quantidade total de linhas
df.describe()  #aqui mostra a média, o desvio padrão, o valor mínimo, os quartis e o valor máximo de cada coluna numérica
df.columns     #aqui mostra o nome de cada coluna

<class 'pandas.DataFrame'>
Index: 660 entries, 0 to 799
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ano          660 non-null    int64
 1   tipo_uva     660 non-null    str
 2   tipo_local   660 non-null    str
 3   categoria    660 non-null    str
 4   volume_hl    660 non-null    float64
 5   valor_usd    660 non-null    float64
 6   local        660 non-null    str
 7   preco_medio  660 non-null    float64
dtypes: float64(3), int64(1), str(4)
memory usage: 46.4 KB

Index(['ano', 'tipo_uva', 'tipo_local', 'categoria', 'volume_hl', 'valor_usd',
       'local', 'preco_medio'],
      dtype='str')

In [32]:
df.isnull().sum()       #aqui mostra a quantidade de valores nulos em cada coluna
df = df.dropna()    #aqui remove as linhas que possuem valores nulos
df = df.drop_duplicates()   #aqui remove as linhas duplicadas, ou seja, as linhas que possuem os mesmos valores em todas as colunas

df['valor_usd'] = pd.to_numeric(df['valor_usd'], errors='coerce')
df['volume_hl'] = pd.to_numeric(df['volume_hl'], errors='coerce')

#  pd.to_numeric(df['valor_usd'], errors='coerce')
#  Existe números em tabelas que vem em forma de texto ou sinais, e o pd.to_numeric() converte esses valores para números, e o errors='coerce' faz com que os valores que não puderem ser convertidos sejam transformados em NaN (Not a Number), ou seja, valores nulos.

In [ ]:
df ['preco_medio'] = df['valor_usd'] / df['volume_hl'] #aqui cria uma nova coluna chamada 'preco_medio' que é o resultado da divisão da coluna 'valor_usd' pela coluna 'volume_hl'

print(df.head()) #aqui mostra as primeiras linhas da tabela, agora com a nova coluna 'preco_medio' criada
print(df['preco_medio'].describe()) #aqui mostra a média, o desvio padrão, o valor mínimo, os quartis e o valor máximo da coluna 'preco_medio'

    ano tipo_uva tipo_local   categoria  volume_hl  valor_usd      local  \
0  2016    Table       Pais  Exportacao     5183.0   399091.0     Italia
1  2016    Table       Pais  Importacao     5752.0   230080.0  Argentina
2  2018    Table       Pais  Importacao     1082.0    47608.0  Argentina
3  2023    Table       Pais  Exportacao     7476.0   142044.0  Argentina
4  2024    Table       Pais  Importacao     2751.0   236586.0    Espanha

   preco_medio
0         77.0
1         40.0
2         44.0
3         19.0
4         86.0
count    660.000000
mean      56.795455
std       24.241369
min       15.000000
25%       36.000000
50%       57.000000
75%       77.000000
max      100.000000
Name: preco_medio, dtype: float64

In [52]:
pd.options.display.float_format = '${:,.2f}'.format #aqui formata os números para serem exibidos com o símbolo de dólar e com duas casas decimais

df.groupby('categoria')['valor_usd'].sum() #aqui agrupa a tabela pela coluna 'categoria' e soma os valores da coluna 'valor_usd' para cada categoria, ou seja, mostra o total de valor em dólares para cada categoria de vinho

categoria
Exportacao   $52,695,456.00
Importacao   $57,341,806.00
Vendas       $64,824,258.00
Name: valor_usd, dtype: float64

In [53]:
pd.options.display.float_format = '${:,.2f}'.format #aqui formata os números para serem exibidos com o símbolo de dólar e com duas casas decimais

df[df['categoria'] != 'vendas'].groupby('categoria')['valor_usd'].sum() #aqui agrupa a tabela pela coluna 'categoria' e soma os valores da coluna 'valor_usd' para cada categoria, mas somente para as categorias que não são 'vendas', ou seja, mostra o total de valor em dólares para cada categoria de vinho, exceto para a categoria 'vendas'

categoria
Exportacao   $52,695,456.00
Importacao   $57,341,806.00
Vendas       $64,824,258.00
Name: valor_usd, dtype: float64

In [54]:
pd.options.display.float_format = '${:,.2f}'.format

df.groupby('ano')['valor_usd'].sum() #aqui agrupa a tabela pela coluna 'ano' e soma os valores da coluna 'valor_usd' para cada ano, ou seja, mostra o total de valor em dólares para cada ano de produção dos vinhos

ano
2015   $15,132,765.00
2016   $19,286,434.00
2017   $20,382,365.00
2018   $19,072,141.00
2019   $14,311,756.00
2020   $16,848,149.00
2021   $18,395,026.00
2022   $20,035,069.00
2023   $13,651,464.00
2024   $17,746,351.00
Name: valor_usd, dtype: float64

In [55]:
pd.options.display.float_format = '${:,.2f}'.format

df.groupby('local')['valor_usd'].sum().sort_values(ascending=False) #aqui agrupa a tabela pela coluna 'local' e soma os valores da coluna 'valor_usd' para cada local, ou seja, mostra o total de valor em dólares para cada local de produção dos vinhos, e depois ordena os resultados em ordem decrescente, ou seja, do local com maior valor em dólares para o local com menor valor em dólares

local
Argentina   $16,531,681.00
Italia      $16,248,962.00
Portugal    $15,173,002.00
Franca      $14,277,913.00
Espanha     $12,528,382.00
Australia   $12,371,090.00
Chile       $12,221,569.00
EUA         $10,684,663.00
RS          $10,301,272.00
SC           $9,878,118.00
GO           $9,266,762.00
SP           $8,348,373.00
PR           $7,739,369.00
MG           $6,999,199.00
BA           $6,414,436.00
PE           $5,876,729.00
Name: valor_usd, dtype: float64

In [ ]:
df.groupby('tipo_uva')['valor_usd'].sum() #aqui agrupa a tabela pela coluna 'tipo_uva' e soma os valores da coluna 'valor_usd' para cada tipo de vinho, ou seja, mostra o total de valor em dólares para cada tipo de vinho

tipo_uva
Table   $90,160,949.00
Wine    $84,700,571.00
Name: valor_usd, dtype: float64

In [68]:
totais_ano = df.groupby('ano')['valor_usd'].sum().reset_index(name='total_valor_usd')
totais_categoria = df.groupby('categoria')['valor_usd'].sum().reset_index(name='total_valor_usd')
with pd.ExcelWriter('vinhos_tratado.xlsx') as writer:
    df.to_excel(writer, sheet_name='dados', index=False)
    totais_ano.to_excel(writer, sheet_name='totais_ano', index=False)
    totais_categoria.to_excel(writer, sheet_name='totais_categoria', index=False)

In [ ]:
df.to_excel('vinhos_tratado.xlsx', index=False) #aqui salva a tabela tratada em um novo arquivo Excel chamado 'vinhos_tratado.xlsx', e o index=False faz com que a coluna de índice não seja salva no arquivo, ou seja, somente as colunas da tabela serão salvas.