In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel('vinhos_desafio.xlsx')    

df

      ano tipo_uva     tipo_local   categoria  volume_hl  valor_usd      local
0    2016    Table           Pais  Exportacao     5183.0   399091.0     Italia
1    2016    Table           Pais  Importacao     5752.0   230080.0  Argentina
2    2018    Table           Pais  Importacao     1082.0    47608.0  Argentina
3    2023    Table           Pais  Exportacao     7476.0   142044.0  Argentina
4    2024    Table           Pais  Importacao     2751.0   236586.0    Espanha
..    ...      ...            ...         ...        ...        ...        ...
795  2016     Wine  Estado_Brasil      Vendas     4294.0   283404.0         PR
796  2020    Table           Pais  Exportacao     5590.0   307450.0  Australia
797  2019    Table           Pais  Exportacao     5331.0   314529.0        EUA
798  2021     Wine           Pais  Importacao     3589.0   333777.0      Chile
799  2024    Table           Pais  Importacao     4465.0   156275.0      Chile

[800 rows x 7 columns]

In [ ]:
df.head(10)

    ano tipo_uva     tipo_local   categoria  volume_hl  valor_usd      local
0  2016    Table           Pais  Exportacao     5183.0   399091.0     Italia
1  2016    Table           Pais  Importacao     5752.0   230080.0  Argentina
2  2018    Table           Pais  Importacao     1082.0    47608.0  Argentina
3  2023    Table           Pais  Exportacao     7476.0   142044.0  Argentina
4  2024    Table           Pais  Importacao     2751.0   236586.0    Espanha
5  2021    Table           Pais  Exportacao     2813.0    92829.0      Chile
6  2016    Table  Estado_Brasil      Vendas     5127.0   333255.0         BA
7  2018     Wine           Pais  Importacao     1029.0    42189.0     Franca
8  2019     Wine           Pais  Importacao     3165.0   259530.0  Argentina
9  2019     Wine           Pais  Importacao      505.0    18180.0      Chile

In [ ]:
df.info()
df.describe()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ano         800 non-null    int64
 1   tipo_uva    800 non-null    str
 2   tipo_local  800 non-null    str
 3   categoria   800 non-null    str
 4   volume_hl   732 non-null    float64
 5   valor_usd   723 non-null    float64
 6   local       800 non-null    str
dtypes: float64(2), int64(1), str(4)
memory usage: 43.9 KB

Index(['ano', 'tipo_uva', 'tipo_local', 'categoria', 'volume_hl', 'valor_usd',
       'local'],
      dtype='str')

In [ ]:
print(df.isnull().sum())

df = df.drop_duplicates()

df['valor_usd'] = pd.to_numeric(df['valor_usd'], errors='coerce')
df['volume_hl'] = pd.to_numeric(df['volume_hl'], errors='coerce')

df = df.dropna(subset=['valor_usd', 'volume_hl'])

ano            0
tipo_uva       0
tipo_local     0
categoria      0
volume_hl     68
valor_usd     77
local          0
dtype: int64

In [ ]:
df = df[df['volume_hl'] > 0]

df['preco_medio'] = df['valor_usd'] / df['volume_hl']

print(df.head())
print(df['preco_medio'].describe())

    ano tipo_uva tipo_local   categoria  volume_hl  valor_usd      local  \
0  2016    Table       Pais  Exportacao     5183.0   399091.0     Italia
1  2016    Table       Pais  Importacao     5752.0   230080.0  Argentina
2  2018    Table       Pais  Importacao     1082.0    47608.0  Argentina
3  2023    Table       Pais  Exportacao     7476.0   142044.0  Argentina
4  2024    Table       Pais  Importacao     2751.0   236586.0    Espanha

   preco_medio
0         77.0
1         40.0
2         44.0
3         19.0
4         86.0
count    660.000000
mean      56.795455
std       24.241369
min       15.000000
25%       36.000000
50%       57.000000
75%       77.000000
max      100.000000
Name: preco_medio, dtype: float64

In [ ]:
pd.options.display.float_format = '${:,.2f}'.format

df.groupby('categoria')['valor_usd'].sum()

categoria
Exportacao   $48,118,441.00
Importacao   $53,735,220.00
Vendas       $58,910,405.00
Name: valor_usd, dtype: float64

In [ ]:
pd.options.display.float_format = '${:,.2f}'.format

df[df['categoria'] != 'vendas'].groupby('categoria')['valor_usd'].sum()

categoria
Exportacao   $48,118,441.00
Importacao   $53,735,220.00
Vendas       $58,910,405.00
Name: valor_usd, dtype: float64

In [ ]:
pd.options.display.float_format = '${:,.2f}'.format

df.groupby('ano')['valor_usd'].sum()

ano
2015   $12,674,946.00
2016   $17,617,922.00
2017   $19,354,987.00
2018   $17,689,633.00
2019   $13,229,750.00
2020   $15,758,370.00
2021   $17,362,207.00
2022   $19,062,749.00
2023   $11,725,940.00
2024   $16,287,562.00
Name: valor_usd, dtype: float64

In [ ]:
pd.options.display.float_format = '${:,.2f}'.format

df.groupby('local')['valor_usd'].sum().sort_values(ascending=False)

local
Italia      $14,651,388.00
Argentina   $14,374,496.00
Franca      $14,094,001.00
Portugal    $14,066,553.00
Australia   $11,808,860.00
Espanha     $11,556,013.00
Chile       $11,337,015.00
EUA          $9,965,335.00
SC           $9,484,574.00
RS           $9,251,541.00
GO           $7,995,588.00
SP           $7,338,141.00
PR           $6,565,181.00
MG           $6,372,707.00
BA           $6,180,436.00
PE           $5,722,237.00
Name: valor_usd, dtype: float64

In [ ]:
df.groupby('tipo_uva')['valor_usd'].sum()

tipo_uva
Table   $82,510,408.00
Wine    $78,253,658.00
Name: valor_usd, dtype: float64

In [15]:
totais_ano = df.groupby('ano')['valor_usd'].sum().reset_index(name='total_valor_usd')
totais_categoria = df.groupby('categoria')['valor_usd'].sum().reset_index(name='total_valor_usd')
with pd.ExcelWriter('vinhos_tratado.xlsx') as writer:
    df.to_excel(writer, sheet_name='dados', index=False)
    totais_ano.to_excel(writer, sheet_name='totais_ano', index=False)
    totais_categoria.to_excel(writer, sheet_name='totais_categoria', index=False)

In [ ]:
df.to_excel('vinhos_tratado.xlsx', index=False)

In [18]:
df1 = pd.read_excel('vinhos_tratado.xlsx')    

df1

,ano,tipo_uva,tipo_local,categoria,volume_hl,valor_usd,local,preco_medio
0,2016,Table,Pais,Exportacao,5183,399091,Italia,77
1,2016,Table,Pais,Importacao,5752,230080,Argentina,40
2,2018,Table,Pais,Importacao,1082,47608,Argentina,44
3,2023,Table,Pais,Exportacao,7476,142044,Argentina,19
4,2024,Table,Pais,Importacao,2751,236586,Espanha,86
...,...,...,...,...,...,...,...,...
655,2016,Wine,Estado_Brasil,Vendas,4294,283404,PR,66
656,2020,Table,Pais,Exportacao,5590,307450,Australia,55
657,2019,Table,Pais,Exportacao,5331,314529,EUA,59
658,2021,Wine,Pais,Importacao,3589,333777,Chile,93
659,2024,Table,Pais,Importacao,4465,156275,Chile,35